# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

#组件信息
component: scf
name: bilibili_tool

#组件参数配置
inputs:
  name: ${name}_scf
  namespace: default
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-guangzhou # 函数所在区域，默认广州
  description: This is a function in ${app} application.
  memorySize: 128
  initTimeout: 30
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  events: # 根据自己的需要修改
    - timer: # 每日任务触发器
        parameters:
          name: DailyTask
          cronExpression: "0 30 12 * * * *"
          enable: true
          argument: Daily
    - timer: # 天选抽奖触发器
        parameters:
          name: LiveLotteryTask
          cronExpression: "0 0 */4 * * * *"
          enable: true
          argument: LiveLottery
    - timer: # 自动取关
        parameters:
          name: UnfollowBatchedTask
          cronExpression: "0 0 0 * * MON *"
          enable: true
          argument: UnfollowBatched
  environment:
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: b_lsid=81F3971F_1800C42B971; _uuid=3615BE91-325D-7D5F-910107-CA5486DF83FA41122infoc; bsource=search_sougo; buvid3=56A24FCA-6034-5A37-F9CA-7DED137671DB41609infoc; b_nut=1649473141; buvid4=7F38B097-4E1A-4729-0088-92E02266EC8B41609-022040910-hpcoWqtaph41Sx8B5JOxZA%3D%3D; sid=6k5jpdp3; fingerprint=421405450c5fe4b38588769ab504b140; buvid_fp_plain=undefined; buvid_fp=bb30faa886e643b267ca564348bd8c58; DedeUserID=451384722; DedeUserID__ckMd5=e5ec6e15c6dbb173; SESSDATA=c58d79bd%2C1665025159%2C31845*41; bili_jct=fc9fc01e67493c250a475a9944878bc1; PVID=1; innersign=0; i-wanna-go-back=-1; b_ut=5; bp_video_offset_451384722=646966128048865300; CURRENT_BLACKGAP=0; CURRENT_FNVAL=80 # cookie，必填
